defaults:
  - override hydra/launcher: joblib

seed: 42

wandb:
  project: "transformer-graph-learner"
  entity: "L65_Project"
  group: "max_epoch_investigation"

dataset:
  num_graphs: 10000
  d_p: 64
  d_e: 1024
  node_id_encode: "orf"
  in_feat_dim: 1
  split: 0.8
  n_nodes_range: [8, 8]


training:
  epoch: &num_epochs 1000
  num_epochs: *num_epochs
  batch_size: 1024
  lr: 2e-4
  weight_decay: 0.1
  device: "cuda"  # set to "cpu" if you don't want to use CUDA
  save_every: 50

model:
  d_model: 1024
  nhead: 16
  num_layers: 5
  dropout: 0.1
  input_dropout: 0.1

scheduler:
  warmup_steps: 300  # Check the num_epochs and adjust this value accordingly


paths:
  models: "models"
