defaults:
  - override hydra/launcher: joblib
  
seed: 1

wandb:
  project: "transformer-graph-learner"
  entity: "L65_Project"
  group: "gcn-hypsearch_num_graphs"

dataset:
  num_graphs: 40_000
  split: 0.8
  n_nodes_range: [128, 128]
  eccentricity: 8  # null for no restriction
  m: 1
  p: 0.15
  q: 0

training:
  epoch: &num_epochs 30000
  num_epochs: *num_epochs
  batch_size: 128
  lr: 2e-4
  weight_decay: 0.1
  device: "cuda"  # set to "cpu" if you don't want to use CUDA
  save_every: 50
  early_stopping:
    enabled: true
    patience: 30
    verbose: false
    min_delta: 0

model:
  d_model: 512
  num_layers: 5

scheduler:
  warmup_steps: null  # Check the num_epochs and adjust this value accordingly

paths:
  models: "models/gcn"
